apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
    name: currently-working-on-db-prd # DopplerSecret Name
    namespace: doppler-operator-system
spec:
    tokenSecret: # Kubernetes service token secret (namespace defaults to doppler-operator-system)
        name: currently-working-on-db-prd
    managedSecret: # Kubernetes managed secret (will be created if does not exist)
        name: currently-working-on-db-prd
        namespace: currently-working-on # Should match the namespace of deployments that will use the secret
        type: Opaque # Optional: defaults to `Opaque` so can be left out unless changed
